#!/bin/bash
#!/bin/sh
#lolcat header, depends on lolcat and figlet


LOLCAT=/usr/games/lolcat

#/usr/bin/env figlet -f isometric3 "ADLER" | $LOLCAT -f
#/usr/bin/env figlet -f isometric3 "adler" | $LOLCAT -f
printf '\n\n'
/usr/bin/env figlet -f roman "adler" | $LOLCAT -f
#printf '\n'