[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-a = "straight-top-serifed"
capital-b = "more-asymmetric-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "short-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-connected-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "crossing"
capital-r = "straight-motion-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-vertical-sides-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-tailed"
b = "toothless-corner"
c = "bilateral-inward-serifed"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-serifed"
g = "double-storey-open"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifed"
k = "curly-serifed"
l = "serifed-diagonal-tailed"
m = "top-left-and-bottom-right-serifed"
n = "straight-motion-serifed"
p = "motion-serifed"
q = "earless-corner-diagonal-tailed"
r = "corner-hooked-top-serifed"
s = "unilateral-inward-serifed"
t = "diagonal-tailed"
u = "toothless-rounded-motion-serifed"
v = "straight-motion-serifed"
w = "straight-flat-top"
x = "straight-motion-serifed"
y = "straight-turn"
z = "curly-serifed"
long-s = "flat-hook"
eszet = "traditional-flat-hook"
lower-iota = "zshaped"
lower-lambda = "straight-turn"
cyrl-capital-u = "straight-turn"
zero = "reverse-slashed"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-crossbar"
eight = "two-circles"
nine = "closed-contour"
asterisk = "penta-low"
underscore = "above-baseline"
pilcrow = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted-open"
ampersand = "upper-open"
at = "threefold-tall"
dollar = "open-cap"
percent = "rings-continuous-slash-also-connected"
question = "corner"
punctuation-dot = "square"
lig-equal-chain = "with-notch"

  [buildPlans.iosevka-custom.ligations]
  inherits = "dlig"
